services:
  - type: web
    name: davel-library
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://davel-library.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
